### ISSUE TITLE
BACKUP_HOST and BACKUP_USER configuration did not take effect in k8s

### ISSUE THREAD

**Issue by xyfleet** [hanchuanchuan/goInception#665]
**描述**
Hello team, 
I installed the goInception using the chart[https://github.com/douban/charts/tree/master/charts/goinception] in my k8s cluster. (I installed the Archery and goinception together.)
The goinception pod did not take the env variables(BACKUP_USER, BACKUP_HOST...) from the values.yaml in the chart. When you check the file, config.toml under etc directory in the pod, you can see this:

```
/etc # ls -ltsa
    12 -rw-r--r--    1 root     root         11705 May  4 16:04 config.toml
```

```
[inc]
backup_host = ""
backup_port = 0
backup_user = ""
backup_password = ""
```

Not sure why the pod did not take the values from the values.yaml. Below is the part of values.yaml in the chart

```
initEnv:
    - name: BACKUP_HOST
      value: "backup_mysql_endpoint"
    - name: BACKUP_PORT
      value: "3306"
    - name: BACKUP_USER
      value: "goinception"
    - name: BACKUP_PASSWORD
      value: "xxxxxx"
```

In the same directory, etc, the file, config.toml, in the folder, goinception, is empty. 
```
/etc/goinception # ls -ltsa
total 0
     0 drwxr-xr-x    1 root     root            25 Aug  1 06:00 ..
     0 drwxrwxrwx    2 root     root            25 Aug  1 06:00 .
     0 -rw-r--r--    1 root     root             0 Aug  1 06:00 config.toml
```

One more question about the BACKUP_HOST. In my case, I have several databases running on my DB instance. One for Archery, one for my application DB, the third one is the database designated for the goinception backup. I am quite confused about what host I should use? 

`xxxx-mysql-1.xxxx.rds.xxxx-xxx-xxx.amazonaws.com`
or
`xxxx-mysql-1.xxxx.rds.xxxx-xxx-xxx.amazonaws.com:3306/goinception`
or something else? I tried both, the running pod did not take any one. 

**重现**
Install the chart in k8s, you can reproduce the issue.

**环境**
 - 数据库: [mysql]
 - 版本: [5.7]

**参数**
